### ISSUE TITLE
Opening bs12's torch-1.dmm crashes the application

### ISSUE THREAD

**Issue by HeyBanditoz** [SpaiR/StrongDMM#32]
Opening `maps/torch/torch1_deck5.dmm` at commit https://github.com/Baystation12/Baystation12/commit/80e2f51a4c2c2e62e7112f2781ba9d9dac471115 crashes the application. It gives the following stacktrace:
```
13:43:52.029 [main] ERROR strongdmm.StrongDMM$Companion - Unhandled exception
kotlin.KotlinNullPointerException: null
	at strongdmm.byond.dmm.parser.TGMParser.parse(TGMParser.kt:45)
	at strongdmm.byond.dmm.parser.DmmParser.parse(DmmParser.kt:12)
	at strongdmm.service.map.MapHolderService$handleOpenMap$1.invoke(MapHolderService.kt:170)
	at strongdmm.service.map.MapHolderService$handleOpenMap$1.invoke(MapHolderService.kt:28)
	at strongdmm.event.Event.reply(Event.kt:26)
	at strongdmm.service.EnvironmentService.handleFetchOpenedEnvironment(EnvironmentService.kt:46)
	at strongdmm.service.EnvironmentService.access$handleFetchOpenedEnvironment(EnvironmentService.kt:15)
	at strongdmm.service.EnvironmentService$2.invoke(EnvironmentService.kt:20)
	at strongdmm.service.EnvironmentService$2.invoke(EnvironmentService.kt:15)
	at strongdmm.event.EventBus.notify(EventBus.kt:19)
	at strongdmm.event.EventHandler$DefaultImpls.sendEvent(EventHandler.kt:13)
	at strongdmm.service.map.MapHolderService.sendEvent(MapHolderService.kt:28)
	at strongdmm.service.map.MapHolderService.handleOpenMap(MapHolderService.kt:169)
	at strongdmm.service.map.MapHolderService.access$handleOpenMap(MapHolderService.kt:28)
	at strongdmm.service.map.MapHolderService$2.invoke(MapHolderService.kt:44)
	at strongdmm.service.map.MapHolderService$2.invoke(MapHolderService.kt:28)
	at strongdmm.event.EventBus.notify(EventBus.kt:19)
	at strongdmm.event.EventHandler$DefaultImpls.sendEvent(EventHandler.kt:13)
	at strongdmm.ui.dialog.available_maps.ViewController.sendEvent(ViewController.kt:10)
	at strongdmm.ui.dialog.available_maps.ViewController.doOpenSelectedMapAndDispose(ViewController.kt:19)
	at strongdmm.ui.dialog.available_maps.View.process(View.kt:54)
	at strongdmm.ui.dialog.available_maps.AvailableMapsDialogUi.process(AvailableMapsDialogUi.kt:17)
	at strongdmm.StrongDMM.appLoop(StrongDMM.kt:100)
	at strongdmm.window.AppWindow.loop(AppWindow.kt:274)
	at strongdmm.window.AppWindow.start(AppWindow.kt:71)
	at strongdmm.StrongDMM$Companion.main(StrongDMM.kt:115)
	at strongdmm.StrongDMM.main(StrongDMM.kt)
```

**Comment by SpaiR** [comment]
I would fix the parser on the editor side. But here is the cause: 
![image](https://user-images.githubusercontent.com/12721311/81080558-86ee8180-8ef9-11ea-8aae-e211fe51144f.png)

Don't know why, but there are several empty lines in the map file.
