### ISSUE TITLE
Logs are not written to file

### ISSUE THREAD

**Issue by DamianX** [SpaiR/StrongDMM#77]
Steps to reproduce:
- Make StrongDMM crash
- Open the `~/.strongdmm/logs` directory, find nothing

I assume the following error is responsible for this:
```
10:02:18,906 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:02:18,906 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:02:18,906 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/D:/dev/StrongDMM/build/install/strong-dmm-shadow/lib/strongdmm.jar!/logback.xml]
10:02:18,917 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1edb61b1 - URL [jar:file:/D:/dev/StrongDMM/build/install/strong-dmm-shadow/lib/strongdmm.jar!/logback.xml] is not of type file
10:02:18,960 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:02:18,960 |-INFO in ch.qos.logback.core.joran.action.TimestampAction - Using current interpretation time, i.e. now, as time reference.
10:02:18,967 |-INFO in ch.qos.logback.core.joran.action.TimestampAction - Adding property to the context with key="byDay" and value="2020.10.23T10:02:18" to the LOCAL scope
10:02:18,968 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:02:18,977 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:02:18,981 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:02:18,997 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
10:02:19,000 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
10:02:19,001 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:02:19,001 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [C:\Users\dm\.strongdmm\logs\sdmm-2020.10.23T10:02:18.log]
10:02:19,003 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(C:\Users\dm\.strongdmm\logs\sdmm-2020.10.23T10:02:18.log,true) call failed. java.io.FileNotFoundException: C:\Users\dm\.strongdmm\logs\sdmm-2020.10.23T10:02:18.log (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileNotFoundException: C:\Users\dm\.strongdmm\logs\sdmm-2020.10.23T10:02:18.log (The filename, directory name, or volume label syntax is incorrect)
	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at 	at strongdmm.StrongDMM$Companion.main(StrongDMM.kt:131)
	at 	at strongdmm.StrongDMM.main(StrongDMM.kt)
10:02:19,003 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
10:02:19,003 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
10:02:19,003 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:02:19,003 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:02:19,004 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@32f61a31 - Registering current configuration as safe fallback point
```

**Comment by SpaiR** [comment]
Fixed here: b7ec854a6c342dc124357ea9f3233a89fc86b068
