### ISSUE TITLE
[Crush] StrongDDM does not check DMI file versions and just crushes

### ISSUE THREAD

**Issue by Gesugao-san** [SpaiR/StrongDMM#92]
# My OS specifications

**OS**: Windows 20H2 (build 19042.1110)
 ├ **BYOND**: 514.1561 (Beta)
 └ **WSL**: Ubuntu 20.04.2 LTS
**StrongDMM**: v1.9.1 [revision: e1a3ea8]
 └ **StrongDMM Launcher**: (v1.1.0) [01693a4]

# Description of the problem itself

I was trying to compile an old [Space Station 13](http://www.byond.com/games/Exadv1/SpaceStation13) build called "[OpenSS13](https://github.com/mloc/openss13)" to try to upload it to a [web map](https://github.com/AffectedArc07/SS13WebMap). Faced with the fact that when opening [this map](https://github.com/mloc/openss13/blob/master/ss13h_new.dmp) _(of course, after analyzing the contents by viewing the file in text format, and changing the extension from ".dmp" to ".dmm")_, [StrongDDM](https://github.com/SpaiR/StrongDMM) simply crashes without explaining the reasons, began to sort out all possible reasons.

# How I was able to deal with this problem

The clue was that when trying to render the [map](https://github.com/mloc/openss13/blob/master/ss13h_new.dmp), the [Map Renderer](https://github.com/SpaceManiac/SpacemanDMM/blob/master/src/cli) from [SpacemanDMM](https://github.com/SpaceManiac/SpacemanDMM) indicated that it could not open one particular file → "**Icons/wall.dmi**".

## Backtrace

```bash
root@Gesu-PC:/mnt/c/Users/Public/Documents/Projects/GitHub/openss13# export RUST_BACKTRACE=full
root@Gesu-PC:/mnt/c/Users/Public/Documents/Projects/GitHub/openss13# './../SpacemanDMM/target/release/dmm-tools' 'minimap' './_ss13h_new.dmm'
parsing spacestation13.dme
./_ss13h_new.dmm
    rendering from 1,1,1 to 100,100,8
    generating z=1
error loading icon: Icons/wall.dmi
  incorrect PNG signature, it''s no PNG or corrupted
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/dreammaker/dmi.rs:427:69
stack backtrace:
   0:     0x564d2de729d5 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x564d2de729d5 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564d2de729d5 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564d2de729d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564d2dd51d1f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x564d2de721b4 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x564d2de71c8b - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x564d2de71c8b - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x564d2de71c8b - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x564d2de71005 - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x564d2de71005 - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x564d2de8c678 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x564d2de8c5ec - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x564d2de8c59d - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x564d2dce7120 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x564d2dce7812 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x564d2de19936 - dreammaker::dmi::Metadata::from_file::h25c9127ab4244cc5
  17:     0x564d2dd64e04 - dmm_tools::icon_cache::load::h0e336245dcb66a96
  18:     0x564d2dd72b7f - dmm_tools::minimap::generate::h8de6c452d04fe0bb
  19:     0x564d2dd08ab6 - dmm_tools::run::{{closure}}::{{closure}}::hffb01489b367a23e
  20:     0x564d2dd0b80b - dmm_tools::run::{{closure}}::h1fb85c6842a74c22
  21:     0x564d2dd077e2 - dmm_tools::main::h5932087c80914194
  22:     0x564d2dd87983 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc246333700c669c
  23:     0x564d2dd0c211 - main
  24:     0x7f8a384880b3 - __libc_start_main
  25:     0x564d2dcf5d0e - _start
  26:                0x0 - <unknown>
root@Gesu-PC:/mnt/c/Users/Public/Documents/Projects/GitHub/openss13#
```

After I tried to modify and save [problematic file](https://github.com/mloc/openss13/blob/master/Icons/wall.dmi), [DreamMaker](https://secure.byond.com/) informed me that this file is in the old format (**DMI v3** instead of **DMI v4**):

![dreammaker_sviGiCbuQK](https://user-images.githubusercontent.com/28023014/126893205-05fb701b-3cdf-49e3-a777-2fe9e48e10d1.png)

With which I agreed by re-saving the file.

# The suggested solution
Research the difference between the two formats and introduce a version check for each ".dmi" file.

---

#### Post Scriptum
But after saving the file, when you try to use Map Renderer again, it still gives an error, no longer specifying the file... But I think that if you resave all the ".dmi" files in this way, the problem will go away.

```bash
root@Gesu-PC:/mnt/c/Users/Public/Documents/Projects/GitHub/openss13# export RUST_BACKTRACE=full
root@Gesu-PC:/mnt/c/Users/Public/Documents/Projects/GitHub/openss13# './../SpacemanDMM/target/release/dmm-tools' 'minimap' './_ss13h_new.dmm'
parsing spacestation13.dme
./_ss13h_new.dmm
    rendering from 1,1,1 to 100,100,8
    generating z=1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/dreammaker/dmi.rs:427:69
stack backtrace:
   0:     0x564424b319d5 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x564424b319d5 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564424b319d5 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564424b319d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564424a10d1f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x564424b311b4 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x564424b30c8b - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x564424b30c8b - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x564424b30c8b - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x564424b30005 - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x564424b30005 - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x564424b4b678 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x564424b4b5ec - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x564424b4b59d - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x5644249a6120 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x5644249a6812 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x564424ad8936 - dreammaker::dmi::Metadata::from_file::h25c9127ab4244cc5
  17:     0x564424a23e04 - dmm_tools::icon_cache::load::h0e336245dcb66a96
  18:     0x564424a31b7f - dmm_tools::minimap::generate::h8de6c452d04fe0bb
  19:     0x5644249c7ab6 - dmm_tools::run::{{closure}}::{{closure}}::hffb01489b367a23e
  20:     0x5644249ca80b - dmm_tools::run::{{closure}}::h1fb85c6842a74c22
  21:     0x5644249c67e2 - dmm_tools::main::h5932087c80914194
  22:     0x564424a46983 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc246333700c669c
  23:     0x5644249cb211 - main
  24:     0x7f83a838d0b3 - __libc_start_main
  25:     0x5644249b4d0e - _start
  26:                0x0 - <unknown>
root@Gesu-PC:/mnt/c/Users/Public/Documents/Projects/GitHub/openss13#
```

**Comment by Gesugao-san** [comment]
Here is a alleged example of the visual difference between the two ".dmi" file formats that VS Code was able to show.

"Icons/turfs.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895264-55bca0a6-2316-4a71-aea7-1877ea849dda.png)

**Comment by Gesugao-san** [comment]
"Icons/ammo.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895567-6105f3bb-d714-4996-ab1a-9a0783ccc36e.png)

**Comment by Gesugao-san** [comment]
"Icons/ammo.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895642-4f0ca5a4-e3e9-4012-9d2b-0675ac4a771d.png)

**Comment by Gesugao-san** [comment]
"Icons/ghost.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895663-68c1bcaf-20b2-413b-9c48-3349964b1944.png)

**Comment by Gesugao-san** [comment]
"Icons/hi_pipe.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895696-81bc2035-c339-4ff9-8524-087d70b7e063.png)

**Comment by Gesugao-san** [comment]
"Icons/human.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895721-c3dc63f3-c9cf-4cef-b7d4-5cc94e647dd9.png)

**Comment by Gesugao-san** [comment]
"Icons/meteor.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895758-53e0e580-cb2e-41b3-bb51-66ccda934c90.png)

**Comment by Gesugao-san** [comment]
"Icons/shards.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895837-003cecc3-dcbc-49e4-86a5-0d3ba2173ae4.png)

**Comment by Gesugao-san** [comment]
"Icons/table.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895861-12964a62-db17-4033-8292-b9c6a1dc900d.png)

**Comment by Gesugao-san** [comment]
"Icons/zone_sel.dmi"
![image](https://user-images.githubusercontent.com/28023014/126895906-42910fc7-0f06-4233-9ae5-76e29359f6d2.png)

**Comment by Gesugao-san** [comment]
How to make the ViS Code display dmi files:
![image](https://user-images.githubusercontent.com/28023014/127818126-a143cb97-988a-4ab3-acc1-f0db4caaef42.png)

**Comment by Gesugao-san** [comment]
Logs:
[sdmm-2021.07.29-13.34.59.log](https://github.com/SpaiR/StrongDMM/files/6944755/sdmm-2021.07.29-13.34.59.log)
[sdmm-2021.07.15-15.10.09.log](https://github.com/SpaiR/StrongDMM/files/6944756/sdmm-2021.07.15-15.10.09.log)

**Comment by SpaiR** [comment]
Old DMI versions won't be supported. Crush processing can be added though. (I think I've already did it for a new version, not sure).
